name=input("Enter the Name of the student ")
date=input("Enter the date ")
place=input("Enter the place ")
froma=input("Enter the From address ")
toa=input("Enter the To address ")
res=input("Enter Respected sir/madam ")
reason=input("Enter the reason ")
days=int(input("Enter how many days "))
print("---------------------------------------------------------------------------------------------")
print("\t\t\t\tLeave letter")
print("---------------------------------------------------------------------------------------------")
print("From:")
print("\t",name)
print("\t",froma)
print("\nTo:")
print("\t",toa)
print("\nRespected",res)
print("\n\tsubject:")
print("I am suffering from",reason,"so i am unable to come to school. so kindly grant me leave for",days,"days")
print("\n\t\t\t\tThank You")
print("\nDate:",date,"\t\t\t\t\t\tYours Faithfully")
print("Place:",place,"\t\t\t\t\t\t",name)
print("---------------------------------------------------------------------------------------------")
