print("--------------------------------------------------------------------------------")
print("\t\t\t\tSTUDENT INFORMATION")
print("--------------------------------------------------------------------------------")
print("\t\t\tNAME\t\t:\tCLEMENT")
print("\t\t\tAGE\t\t:\t29")
print("\t\t\tEMAIL\t\t:\tmariaclementraj@gamil.com")
print("\t\t\tADDRESS\t\t:\tratna nagar, puducherry")
print("\t\t\tMOBILE NO\t:\t9976816914")
print("--------------------------------------------------------------------------------")


print("\t\t\t\tLeave letter")
print("--------------------------------------------------------------------------------")
print("From:")
print("\tA.Maria Clement Raj")
print("\t12th student")
print("\tDon Bosco school")
print("\tChennai")
print("To:")
print("\tThe Class Teacher")
print("\t12th student")
print("\tDon Bosco school")
print("\tChennai")
print("Respected sir,")
print("\tsubject:")
print("I am suffering from fever so i am unable to come to today. so kindly grant me leave for today")
print("\t\t\t\tThank You")
print("Date:24-03-25023\t\t\t\t\t\tYours Faithfully")
print("Place:Chennai\t\t\t\t\t\t\tClement")
print("--------------------------------------------------------------------------------")
